version: "3.8"

networks:
  trainingNetwork:
    external: true

services:
  server:
    image: gitea/gitea:1.21.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=America/Bogota
    restart: always
    networks:
      - trainingNetwork
    volumes:
      - ./gitea:/data
    ports:
      - "3001:3000"
      - "222:22"

volumes:
  onlyJava:
    external: true
      # ./gitea:/data
